### ISSUE TITLE
Steering algorithm should be optimized

### ISSUE THREAD

**Issue by MarcAntony27** [Rapid-Cars/Rapid3#2]
One part of the steering algoritm is following calculation:
```
dif = left_averages[1] - left_averages[2]
relative = left_averages[0] / (left_averages[1] + dif)
```
where the averages are 3 x-coordinates of the lane. left_averages[0] is the most upper one, left_averages[2] the lowest one. 
The problem is, that the denominator can be 0 (, which is also the relatively most probable case). 

Irrelevant: The new idea involves use of the arctan function. For that we would only need two x-coordinates but also the corresponding y-coordinates, so the code would have to be reworked a little. Using the arctan would also need no exception for denominator = 0, because if you put the y-coordinates in there, there can't be a 0.

**Comment by robmroi** [comment]
- Verwende Absätze
- Schreibe den Code nicht als Plaintext ins Issue
- Sage aus welcher Datei und in welchen Zeilen der angegebene Code herkommt
- Die neue Idee hat außerdem nichts mit dem Issue zu tun, hierfür also irrelevant
- Hat auch nichts mit dem Issue zu tun: Lad endlich deinen eigenen Code hoch.

**Comment by robmroi** [comment]
Zur Problembehandlung:
Überprüfe ob 
`left_averages[1] + dif == 0` true ist. Wenn nein, kannst du den Code ausführen, wenn ja würde ich ausgeben lassen was die Werte sind, damit man den Fall rausfindet wo das stattfindet. 

Sobald man das weis, kann man folgende Dinge tun
- Ignorieren
- Relative auf einen bestimmten Wert setzen
- Den Wert +- einen Wert rechnen und anschließend die Operation ausführen

**Comment by robmroi** [comment]
Was probably solved.
